name: Dagger CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ci:
    name: Run CI Pipeline
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dagger
      run: |
        curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.18.14 sh
        sudo mv bin/dagger /usr/local/bin
        dagger version

    - name: Run CI Pipeline
      run: |
        dagger call full-ci-pipeline --source=.
